### PR TITLE
Deleted Worldclass.ts from the top-level shared directory.

### LINKED ISSUE #322: Delete the `src/shared/constants/WordClass` file
## Background
There are two `WordClass` files that exist in the database — one in the `backend` directory and another in the top-level `shared` directory.

## Ideal Solution
Remove `src/shared/constants/WordClass` to only have `src/backend/shared/constants/WordClass`. Once the file has been deleted, you will need to update all the paths that pointed to the now deleted file to the existing `WordClass` file.

### PR DESCRIPTION
**Pull request by giri-madhan**
| Status  | Type  | Env Vars Change | Ticket |
| :---: | :---: | :---: | :--: |
| Ready | Refactor | No | Closes #322 |

## Problem

_There is an extra WorldClass.ts file from the top-level shared directory._

## Solution

_Deleted Worldclass.ts from the top-level shared directory._

### CODE REVIEW

**Review by ijemmao — CHANGES_REQUESTED** [review]
great start!

you'll need to update all the files that pointed to this file

I recommend that you run this project locally and then run the tests locally to confirm that you don't have a breaking change

**Comment by giri-madhan** [comment]
Hi @ijemmao,

I tried setting up the frontend and backend locally, but I am having trouble with the setup process. Would it be alright if I closed this pull request?

**Comment by giri-madhan** [comment]
As a first-time contributor, I'm feeling a little confused about setting up Firebase for both the frontend and backend of a project. Specifically, I'm not sure if I should create two Firebase projects for the frontend and if those same two can be used for the backend as well, or if I need to create another one (three in total) for the backend. @ijemmao

**Comment by ijemmao** [comment]
@giri-madhan that's fair feedback. You technically only need one Firebase project that will be used for all aspects of the project (frontend and backend)

But I will update the docs to better explain the expected use of the projects. Thanks for the feedback though!

Hopefully a new issue will arise in the future that you can knock out~

**Pull request closed without merging**
