### PR TITLE
Added buttons for data collection Call to action buttons

### LINKED ISSUE #263: Create Show View for Data Collection
**Is your feature request related to a problem? Please describe.**
We want to have a simplistic way of collecting a lot of Igbo audio data within the Igbo API Editor Platform. The best way is to have an intuitive user experience that streamlines the process of recording or verifying audio data.

**Describe the solution you'd like**
When a user navigates to the Data collection page, they will have the option to either:
1. Record audio for existing example suggestions that don't have audio, or
2. Verify (approve or deny) example suggestions that do have audio recorded

These should just be two buttons that will have the ability to navigate to another page. For the sake of this PR, there's no need to actually have these buttons navigate to any page.

**Additional context**
This PR relies on #262 being completed. So the majority of the logic can be written out, but the last 5% will be to place this show view within the new "Data Collection" Resource tab that @mazma1  is working on.

### PR DESCRIPTION
**Pull request by Robertito1**
Working towards the Data collection feature that enables users to add 

Closes #263

### CODE REVIEW

**Comment by mazma1** [comment]
@Robertito1 is there a way to get to the `Show` page?

**Comment by Robertito1** [comment]
> @Robertito1 is there a way to get to the `Show` page?

Not right now, currently the data collection tab leads to the a list page, I was of the impression that it should lead to the show page. So I decided to not modify the list page and just include the Show page in the resources file

**Comment by mazma1** [comment]
Oh, I see! I probably missed it from my own task, I assumed we get to a `Show` page only by clicking an item on a `List` page.

@ijemmao is this assumption correct? Can we just render a `Show` page for a resource?

**Comment by ijemmao** [comment]
@Robertito1 seems there are some merge conflicts? We have the `DataCollection` component already that's our show view - that's where you want to place the buttons

**Pull request closed without merging**
